### ISSUE TITLE
Deno.emit is not a function

### ISSUE THREAD

**Issue by chris-carrington** [skymethod/denoflare#14]
Thank you for creating this!

I run `denoflare serve hello-local` & the result is 

```
Compiling https://raw.githubusercontent.com/skymethod/denoflare/v0.4.5/cli-webworker/worker.ts into worker contents...
error: Uncaught (in promise) TypeError: Deno.emit is not a function
    const result = await Deno.emit(rootSpecifier, {
                              ^
    at emit (https://raw.githubusercontent.com/skymethod/denoflare/v0.4.5/cli/emit.ts:3:31)
    at Function.start (https://raw.githubusercontent.com/skymethod/denoflare/v0.4.5/cli/worker_manager.ts:30:32)
    at createLocalRequestServer (https://raw.githubusercontent.com/skymethod/denoflare/v0.4.5/cli/cli_serve.ts:122:55)
    at serve (https://raw.githubusercontent.com/skymethod/denoflare/v0.4.5/cli/cli_serve.ts:155:38)
    at async https://raw.githubusercontent.com/skymethod/denoflare/v0.4.5/cli/cli.ts:16:13
```

**Comment by chris-carrington** [comment]
.denoflare

```
{
  "$schema": "https://raw.githubusercontent.com/skymethod/denoflare/v0.4.5/common/config.schema.json",
  "scripts": {
      "hello-local": {
        "path": "index.ts",
        "localPort": 3030
      }
  },
  "profiles": {
      "account1": {
        "accountId": "abc",
        "apiToken": "123"
      }
  }
}
```

index.ts

```
export default {
  async fetch(request: Request, env: any) {
      try {
          return new Response('hi')
      } catch (e) {
          return new Response(e.message)
      }
  },
}
```

deno --version

```
deno 1.22.0 (release, x86_64-apple-darwin)
v8 10.0.139.17
typescript 4.6.2
```

**Comment by johnspurlock-skymethod** [comment]
Congratulations, you've updated Deno to their latest cutting edge release!

Deno just removed `Deno.emit` from the latest version 1.22.0: https://deno.com/blog/v1.22#removal-of-unstable-denoemit-denoformatdiagnostics-and-denoapplysourcemap-apis

They have a new userland replacement module, but it is nowhere near the same functionality.

https://github.com/denoland/deno_emit

I have been filing issues all day : )

I had no idea this was coming, so have been looking at workarounds this morning.  I have enough in there that you can try installing denoflare from the latest commit and it _should_ work on both 1.22 and earlier - but I'd appreciate any bug reports you have on that version too.  Even when the new userland module works, it doesn't seem to typecheck

If all else fails, you can also `deno upgrade --version 1.21.3` to downgrade to the prior stable Deno version

**Comment by chris-carrington** [comment]
Yay! That worked! Thank you! I think you're project is one of the best ever btw! Thank you for integrating Deno & Cloudflare for free!

**Comment by johnspurlock-skymethod** [comment]
Nice! Just curious, which did you do? Running latest denoflare or downgrade Deno?

If you get value out this project, consider a [supporting donation](https://denoflare.dev/#support-this-project)!

**Comment by chris-carrington** [comment]
I donated! So I did the downgrade, thank you for that! It initially worked & now it's not working

```
Chriss-MacBook-Pro-2:align-love chris-carrington$ denoflare serve hello-local
Compiling https://raw.githubusercontent.com/skymethod/denoflare/v0.4.5/cli-webworker/worker.ts into worker contents...
Compiled https://raw.githubusercontent.com/skymethod/denoflare/v0.4.5/cli-webworker/worker.ts into worker contents in 1008ms
runScript: index.ts
Error 'Unable to output during bundling.' contains boxed error of unknown type:
  Error { context: "Unable to output during bundling.", source: load_transformed failed

Caused by:
    0: failed to analyze module
    1: failed to resolve ./soon from file:///Users/chris-carrington/cloud/align-love/index.ts
    2: Cannot resolve "./soon" from "file:///Users/chris-carrington/cloud/align-love/index.ts". }
  Error { context: "load_transformed failed", source: failed to analyze module

Caused by:
    0: failed to resolve ./soon from file:///Users/chris-carrington/cloud/align-love/index.ts
    1: Cannot resolve "./soon" from "file:///Users/chris-carrington/cloud/align-love/index.ts". }
  Error { context: "failed to analyze module", source: failed to resolve ./soon from file:///Users/chris-carrington/cloud/align-love/index.ts

Caused by:
    Cannot resolve "./soon" from "file:///Users/chris-carrington/cloud/align-love/index.ts". }
  Error { context: "failed to resolve ./soon from file:///Users/chris-carrington/cloud/align-love/index.ts", source: Cannot resolve "./soon" from "file:///Users/chris-carrington/cloud/align-love/index.ts". }
  "Cannot resolve \"./soon\" from \"file:///Users/chris-carrington/cloud/align-love/index.ts\"."
error: Uncaught (in promise) Error: Unable to output during bundling.
    const result = await Deno.emit(rootSpecifier, {
                   ^
    at async emit (https://raw.githubusercontent.com/skymethod/denoflare/v0.4.5/cli/emit.ts:3:20)
    at async computeScriptContents (https://raw.githubusercontent.com/skymethod/denoflare/v0.4.5/cli/cli_serve.ts:91:26)
    at async runScript (https://raw.githubusercontent.com/skymethod/denoflare/v0.4.5/cli/cli_serve.ts:130:40)
    at async createLocalRequestServer (https://raw.githubusercontent.com/skymethod/denoflare/v0.4.5/cli/cli_serve.ts:138:13)
    at async serve (https://raw.githubusercontent.com/skymethod/denoflare/v0.4.5/cli/cli_serve.ts:155:32)
    at async https://raw.githubusercontent.com/skymethod/denoflare/v0.4.5/cli/cli.ts:16:13
Chriss-MacBook-Pro-2:align-love chris-carrington$ deno --version
deno 1.21.3 (release, x86_64-apple-darwin)
```

**Comment by johnspurlock-skymethod** [comment]
thanks for the donation! 🚀🚀🚀

`failed to resolve ./soon from file:///Users/chris-carrington/cloud/align-love/index.ts`

Make sure you are using deno/esm-style imports: e.g. `import { foo } from ./soon.ts`, not the node-style `import { foo } from ./soon`

**Comment by chris-carrington** [comment]
You're welcome! Thank you so much!
