### ISSUE TITLE
denoflare push does not consult the ENV or flags for account-id and api-token

### ISSUE THREAD

**Issue by myobie** [skymethod/denoflare#47]
While denoflare serve looks into the ENV or the flags for my account-id and api-token, the push command won't see the same ENV vars or flags.

**Comment by johnspurlock-skymethod** [comment]
Can you be more specific?  I believe most of the configuration options between `serve` and `push` are similar

**Comment by myobie** [comment]
@johnspurlock-skymethod using this config:

```jsonc
{
  "$schema": "https://raw.githubusercontent.com/skymethod/denoflare/v0.5.11/common/config.schema.json",
  "scripts": {
    "cache-api-tests": {
      "path": "mod.ts",
      "localPort": 4010,
      "workersDev": true
    }
  },
  "profiles": {}
}
```

I have `CF_API_TOKEN` and `CF_ACCOUNT_ID` set in my environment and when I run `denoflare serve` it discovers them and uses them. Everything works as expected.

<details>
<summary>
Just so it's clear that the ENV vars are working, this is what is output by `denoflare serve` when the ENV vars are not set:
</summary>

```
error: Uncaught (in promise) Error: Error loading config (path=denoflare.jsonc): Bad profiles.account.accountId: undefined
        throw new Error(`Error loading config (path=${path}): ${e.message || e}`);
              ^
    at loadConfigFromFile (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.11/cli/config_loader.ts:111:15)
    at async loadConfig (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.11/cli/config_loader.ts:25:35)
    at async Object.serve [as handler] (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.11/cli/cli_serve.ts:65:20)
    at async CliCommand.routeSubcommand (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.11/cli/cli_command.ts:104:13)
    at async https://raw.githubusercontent.com/skymethod/denoflare/v0.5.11/cli/cli.ts:33:5
```

</details>

When I run `denoflare push` it first says it cannot find a profile:

```
error: Uncaught (in promise) Error: Unable to find profile, no profiles in config
    if (profile === undefined) throw new Error(`Unable to find profile, no profiles in config`);
                                     ^
    at resolveProfile (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.11/cli/config_loader.ts:86:38)
    at async Object.push [as handler] (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.11/cli/cli_push.ts:43:37)
    at async CliCommand.routeSubcommand (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.11/cli/cli_command.ts:104:13)
    at async https://raw.githubusercontent.com/skymethod/denoflare/v0.5.11/cli/cli.ts:33:5
```

Even if I give it a profile, it then complains it cannot find the account id:

```jsonc
{
  // ...
  "profiles": {
    "account": {}
  }
}
```

```
error: Uncaught (in promise) Error: Error loading config (path=denoflare.jsonc): Bad profiles.account.accountId: undefined
        throw new Error(`Error loading config (path=${path}): ${e.message || e}`);
              ^
    at loadConfigFromFile (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.11/cli/config_loader.ts:111:15)
    at async loadConfig (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.11/cli/config_loader.ts:25:35)
    at async Object.push [as handler] (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.11/cli/cli_push.ts:40:20)
    at async CliCommand.routeSubcommand (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.11/cli/cli_command.ts:104:13)
    at async https://raw.githubusercontent.com/skymethod/denoflare/v0.5.11/cli/cli.ts:33:5
```

This error matches the error output by `denoflare serve` when the ENV vars are not set.

I've also spelunked some into the code and the way the profile / accountId is discovered is different for push vs. serve. I don't completely understand the nuance, but `serve` uses `resolveProfileOpt()` and `push` uses `resolveProfile()`, for example.

I apologize for not including these details initially, I thought this was a known issue since the code was making different choices in the commands.

**Comment by johnspurlock-skymethod** [comment]
Ok, taking a look...

**Comment by johnspurlock-skymethod** [comment]
Works for me on a brand new machine:
 - install deno, denoflare
 - vim a new worker into hello.ts
 - `export CF_ACCOUNT_ID=<elided>`
 - `export CF_API_TOKEN=<elided>`
 - `denoflare serve hello.ts`   # works
 - `denoflare push hello.ts --name hellotmp` # uses cf account info from env

maybe try `--verbose` in your push call to see if any clues appear there

Note from what I'm seeing in the common `loadConfig` used to init the "env" profile in both `serve` and `push`, this codepath is only used when there are no profiles defined in the config file.

Worst case you can pass the info explicitly using the named command line args (example [here](https://github.com/skymethod/op3/blob/master/deploy.sh#L33))

Hope that helps!
