### ISSUE TITLE
Deno.spawn is not a function when deploying / serving any worker

### ISSUE THREAD

**Issue by Metaphysics0** [skymethod/denoflare#51]
I'm getting the error with the callstack:
```
error: Uncaught (in promise) TypeError: Deno.spawn is not a function
    const rt = await Deno.spawn(command, options) as any;
                          ^
    at spawn (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.10/cli/spawn.ts:12:27)
    at runDenoBundle (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.10/cli/deno_bundle.ts:67:53)
    at denoBundle (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.10/cli/deno_bundle.ts:35:45)
    at async bundle (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.10/cli/bundle.ts:104:35)
    at async Function.start (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.10/cli/worker_manager.ts:38:43)
    at async createLocalRequestServer (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.10/cli/cli_serve.ts:155:35)
    at async Object.serve [as handler] (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.10/cli/cli_serve.ts:188:32)
    at async CliCommand.routeSubcommand (https://raw.githubusercontent.com/skymethod/denoflare/v0.5.10/cli/cli_command.ts:104:13)
    at async https://raw.githubusercontent.com/skymethod/denoflare/v0.5.10/cli/cli.ts:33:5
```
    
 When attempting to publish or serve any worker.

My specs
deno 1.32.4 (release, aarch64-apple-darwin)
v8 11.2.214.9
typescript 5.0.3

OS: Macbook Pro M1

**Comment by johnspurlock-skymethod** [comment]
Deno removed `Deno.spawn` - is there any reason you are not using the latest `denoflare` [release](https://github.com/skymethod/denoflare/tags) version?

ie use `v0.5.11` instead of `v0.5.10` however you install/run denoflare.

**Comment by johnspurlock-skymethod** [comment]
This is really old at this point.

Denoflare supports the latest 1.x and 2.x versions of Deno

👉 [Release v0.7.0](https://github.com/skymethod/denoflare/releases/tag/v0.7.0)

(Consider [supporting this project](https://denoflare.dev/#support-this-project) if you find it useful)
