### ISSUE TITLE
push-deploy has error message when push to empty project

### ISSUE THREAD

**Issue by pd12bbf7608ae1** [skymethod/denoflare#73]
When using push-deploy to deploy to a blank project, the following error occurs:
```js
error: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'deployment')
        const shortestDomainMapping = sortBy(project.productionDeployment.deployment?.domainMappings ?? [], v => v.domain.length).at(0);
                                                                          ^
    at buildAndPutScript (https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/cli_push_deploy.ts:153:75)    at eventLoopTick (ext:core/01_core.js:64:7)
    at async Object.pushDeploy [as handler] (https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/cli_push_deploy.ts:158:5)
    at async CliCommand.routeSubcommand (https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/cli_command.ts:104:13)
    at async https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/cli.ts:41:5
```

**Comment by johnspurlock-skymethod** [comment]
Thanks for reporting!  Fixed in b13bcc477d8a51fdcbf525b89110085743223c49

It will be part of the next tagged release, but you can always run denoflare from a commit: `b13bcc477d8a51fdcbf525b89110085743223c49`
