### ISSUE TITLE
deno 2.0

### ISSUE THREAD

**Issue by q351941406** [skymethod/denoflare#77]
<img width="1138" alt="截屏2024-10-23 00 02 38" src="https://github.com/user-attachments/assets/a30cf33f-634e-4886-b0c8-f757b82670c3">
deno 2.0
denoflare 6

**Comment by q351941406** [comment]
ganzhengwei@ganzhenweisMini ArtifexAIbot % denoflare serve main
✅ Granted all import access.
Compiling https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli-webworker/worker.ts into worker contents...
✅ Granted all write access.
TS0: error: unexpected argument '--config' found

Usage: deno bundle [OPTIONS]


  at undefined:
error: Uncaught (in promise) Error: bundle failed
        throw new Error('bundle failed');
              ^
    at bundle (https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/bundle.ts:108:15)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async Function.start (https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/worker_manager.ts:40:43)
    at async createLocalRequestServer (https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/cli_serve.ts:161:35)
    at async Object.serve [as handler] (https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/cli_serve.ts:194:32)
    at async CliCommand.routeSubcommand (https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/cli_command.ts:104:13)
    at async https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/cli.ts:41:5
ganzhengwei@ganzhenweisMini ArtifexAIbot %

**Comment by soyantonio** [comment]
You can use `esbuild` as the bundle backend. That was added [recently](https://github.com/skymethod/denoflare/commit/827d5b1faebf233f4edd434de7fec7d9f1086483), so for the moment there's no tag/release with those changes

A workaround is to use the commit hash for the installation, something like

```
deno install --global --allow-import=cdn.skypack.dev:443,raw.githubusercontent.com:443,deno.land:443 \
  --allow-write --unstable-worker-options --allow-read --allow-net --allow-env --allow-run \
  --name denoflare --force https://raw.githubusercontent.com/skymethod/denoflare/3a875145982d0b288dd864cb2ef1e00552b59cae/cli/cli.ts
```


Then you can use

```
denoflare serve main --bundle 'backend=esbuild'
```


I tested that using deno `2.0.2`

**Comment by q351941406** [comment]
@soyantonio ganzhengwei@ganzhenweisMini ArtifexAIbot % denoflare serve main
✅ Granted all import access.
Compiling https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli-webworker/worker.ts into worker contents...
✅ Granted all write access.
TS0: error: unexpected argument '--config' found

Usage: deno bundle [OPTIONS]


  at undefined:
error: Uncaught (in promise) Error: bundle failed
        throw new Error('bundle failed');
              ^
    at bundle (https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/bundle.ts:108:15)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async Function.start (https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/worker_manager.ts:40:43)
    at async createLocalRequestServer (https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/cli_serve.ts:161:35)
    at async Object.serve [as handler] (https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/cli_serve.ts:194:32)
    at async CliCommand.routeSubcommand (https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/cli_command.ts:104:13)
    at async https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/cli.ts:41:5
ganzhengwei@ganzhenweisMini ArtifexAIbot % deno -v
deno 2.0.2
ganzhengwei@ganzhenweisMini ArtifexAIbot % deno install --global --allow-import=cdn.skypack.dev:443,raw.githubusercontent.com:443,deno.land:443 \
  --allow-write --unstable-worker-options --allow-read --allow-net --allow-env --allow-run \
  --name denoflare --force https://raw.githubusercontent.com/skymethod/denoflare/3a875145982d0b288dd864cb2ef1e00552b59cae/cli/cli.ts
✅ Successfully installed denoflare
/Users/ganzhengwei/.deno/bin/denoflare
ganzhengwei@ganzhenweisMini ArtifexAIbot % denoflare serve main --bundle 'backend=esbuild'
✅ Granted all import access.
Compiling https://raw.githubusercontent.com/skymethod/denoflare/3a875145982d0b288dd864cb2ef1e00552b59cae/cli-webworker/worker.ts into worker contents...
{
  out: "",
  err: "Download https://raw.githubusercontent.com/skymethod/denoflare/3a875145982d0b288dd864cb2ef1e00552b59cae/cli-webworker/worker.ts\n" +
    "Check https://raw.githubusercontent.com/skymethod/denoflare/3a875145982d0b288dd864cb2ef1e00552b59cae/cli-webworker/worker.ts\n",
  success: true
}
Bundled https://raw.githubusercontent.com/skymethod/denoflare/3a875145982d0b288dd864cb2ef1e00552b59cae/cli-webworker/worker.ts (esbuild) in 8793ms
runScript: /Users/ganzhengwei/Desktop/object/ComfyUI/ArtifexAIbot/main.ts
{
  out: "",
  err: "Download https://esm.sh/itty-router@5.0.18\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/index.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/IttyRouter.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/Router.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/AutoRouter.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/StatusError.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/createResponse.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/error.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/status.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/text.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/json.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/html.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/jpeg.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/png.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/webp.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/withContent.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/withCookies.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/withParams.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/cors.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/AutoRouterOptions.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/AutoRouterType.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/CustomRoutes.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/ErrorHandler.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/IRequest.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/IRequestStrict.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/IttyRouterOptions.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/IttyRouterType.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/RequestHandler.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/ResponseHandler.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/RequestLike.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/Route.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/RouteEntry.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/RouterOptions.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/RouterType.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/HasContent.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/ResponseFormatter.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/ErrorFormatter.d.ts\n" +
    "Download https://esm.sh/v135/itty-router@5.0.18/types/GenericTraps.d.ts\n" +
    "Check file:///Users/ganzhengwei/Desktop/object/ComfyUI/ArtifexAIbot/main.ts\n",
  success: true
}
Bundled /Users/ganzhengwei/Desktop/object/ComfyUI/ArtifexAIbot/main.ts (esbuild) in 3088ms
worker: start
Error running script Error: Bad module.default: undefined
    at Function.create (blob:null/0c58007d-fe63-4856-8e9a-20b546e0545e:564:42)
    at async Function.start (blob:null/0c58007d-fe63-4856-8e9a-20b546e0545e:666:46)
    at async blob:null/0c58007d-fe63-4856-8e9a-20b546e0545e:2854:18
    at async _RpcChannel.receiveMessage (blob:null/0c58007d-fe63-4856-8e9a-20b546e0545e:37:26)
    at async self.onmessage (blob:null/0c58007d-fe63-4856-8e9a-20b546e0545e:2883:9)
ganzhengwei@ganzhenweisMini ArtifexAIbot % denoflare serve main --bundle 'backend=esbuild'
✅ Granted all import access.
Compiling https://raw.githubusercontent.com/skymethod/denoflare/3a875145982d0b288dd864cb2ef1e00552b59cae/cli-webworker/worker.ts into worker contents...
{ out: "", err: "", success: true }
Bundled https://raw.githubusercontent.com/skymethod/denoflare/3a875145982d0b288dd864cb2ef1e00552b59cae/cli-webworker/worker.ts (esbuild) in 148ms
runScript: /Users/ganzhengwei/Desktop/object/ComfyUI/ArtifexAIbot/main.ts
{ out: "", err: "", success: true }
Bundled /Users/ganzhengwei/Desktop/object/ComfyUI/ArtifexAIbot/main.ts (esbuild) in 47ms
worker: start
Error running script Error: Bad module.default: undefined
    at Function.create (blob:null/51ae52bc-1956-4063-916d-8a1ba9e1e658:564:42)
    at async Function.start (blob:null/51ae52bc-1956-4063-916d-8a1ba9e1e658:666:46)
    at async blob:null/51ae52bc-1956-4063-916d-8a1ba9e1e658:2854:18
    at async _RpcChannel.receiveMessage (blob:null/51ae52bc-1956-4063-916d-8a1ba9e1e658:37:26)
    at async self.onmessage (blob:null/51ae52bc-1956-4063-916d-8a1ba9e1e658:2883:9)
ganzhengwei@ganzhenweisMini ArtifexAIbot %

**Comment by ajsb85** [comment]
`deno install` fails for denoflare CLI with `--unstable-worker-options` and permission flags

When attempting to install the denoflare CLI using the command provided in the documentation:

```bash
deno install --unstable-worker-options --allow-read --allow-net --allow-env --allow-run --name denoflare --force \
https://raw.githubusercontent.com/skymethod/denoflare/v0.6.0/cli/cli.ts
```

I encounter the following error:

```
error: the following required arguments were not provided:
  --global

Note: Permission flags can only be used in a global setting
```

It seems that using `--unstable-worker-options` in conjunction with permission flags like `--allow-read` requires the `--global` flag, which is not mentioned in the installation instructions.

**Steps to Reproduce:**

1.  Run the `deno install` command as shown above.
2.  Observe the error message.

**Expected Behavior:**

The denoflare CLI should install successfully without requiring the `--global` flag when using `--unstable-worker-options` and permission flags.

**Actual Behavior:**

The installation fails with the error message indicated above.

**Environment:**

  * **Deno version:**  (Please provide your Deno version: `deno -v`)
  * **OS:** (Please provide your operating system)

**Additional Context:**

This issue may be related to how Deno handles permissions in combination with `--unstable-worker-options`.  Clarification in the documentation or a fix in the installation script would be appreciated.

https://github.com/skymethod/denoflare-docs/blob/HEAD/cli/index.md#installation

**Comment by mstephenson6** [comment]
To get the tutorial hello-local serving on deno 2.1.4, linux aarch64:

1. Ran @soyantonio's `deno install` command above with the latest commit hash
2. Updated `~/.deno/bin/denoflare` to include `jsr.io:443` in the list of hosts for `--allow-import`

**Comment by johnspurlock-skymethod** [comment]
It should work, but make sure you install from the head commit.  Only thing not ported over yet are the wasm/file imports, once that's done, I'll make a new tagged release.

**Comment by johnspurlock-skymethod** [comment]
Finally got a chance to get the magic imports working in deno2 and updated all examples/docs, and cut a new release.

👉 [Release v0.7.0](https://github.com/skymethod/denoflare/releases/tag/v0.7.0)

(Consider [supporting this project](https://denoflare.dev/#support-this-project) if you find it useful)
